mybatis-plus:
  mapper-locations: classpath*:/orm/*Mapper.xml
  type-aliases-package: org.sas.service.logincheck.com.entity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
      
server:
  port: 8762
  
spring:
  application:
    name: service-logincheck
    
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: test
    url: jdbc:mysql://127.0.0.1:3306/sas?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  thymeleaf: 
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
pagehelper:
  helper-dialect: mysql